### ISSUE TITLE
PCAS controller upgrade

### ISSUE THREAD

**Issue by MiyoKouseki** [gw-vis/pcas-controller#2]
池田さんの主な仕事（Auto-offloading System、Temperature Control System）が終わったら、次にしてほしい作業。

* [ ] Motor control for cryo-payload
* [ ] Proper monitor of the accumulated motor steps
* [ ] Easy-to-see information about the motor status
* [ ] **Review**
* [ ] **Close**
